import { type NextPage } from "next";
import Head from "next/head";
import { Footer, Input, Navbar, TierList } from "../components";
import { useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCheck } from "@fortawesome/free-solid-svg-icons";

const Home: NextPage = () => {
  const [name, setName] = useState("");

  return (
    <div className="bg-base-200">
      <Head>
        <title>tier-list-maker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bc container mx-auto flex min-h-screen flex-col items-center bg-base-200 p-4">
        <Navbar />

        <div className="h-full w-full">
          <div className="flex flex-row space-x-2">
            <Input
              placeholder="Tier List Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <button className="btn-square btn">
              <FontAwesomeIcon icon={faCheck} color="white" size="lg" />
            </button>
          </div>

          <div className="divider" />

          <TierList />
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
