import { type NextPage } from "next";
import Head from "next/head";
import { Footer, Input, Navbar, TierList } from "../components";
import { useState } from "react";

const Home: NextPage = () => {
  const [name, setName] = useState("");

  return (
    <div className="bg-base-200">
      <Head>
        <title>tier-list-maker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bc container mx-auto flex min-h-screen flex-col items-center bg-base-200 p-4">
        <Navbar />

        <div className="h-full w-full">
          <div className="flex flex-row space-x-2">
            <Input
              placeholder="Tier List Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            {/* TODO: Change icon to accept */}
            <button className="btn-square btn">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>

          <div className="divider" />

          <TierList />
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
